# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [813]:
# Use this cell for your code
import numpy as np
# IF 1e7 = 10,000,000, then 1e7-1 means 9,999,999
A = list(range(int(1e7)))
B = list(range(int(1e7)))

print("The result using normal lists to print out the array:", A[:5], "...", A[-5:])

The result using normal lists to print out the array: [0, 1, 2, 3, 4] ... [9999995, 9999996, 9999997, 9999998, 9999999]


2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [814]:
def add_with_for(A, B):
    C = []
    for i in range(len(A)): # added a for loop function
        C.append(A[i] + B[i])
    return C

# defining the elements of A and B arrays
A = [0, 1, 2, 3, 4]
B = [0, 1, 2, 3, 4]

C = add_with_for(A, B)
print("The result:", C) #should contain the integers 0, 2, 4, etc... to match the condition.

The result: [0, 2, 4, 6, 8]


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [815]:
# Use this cell for your code
def add_with_numpy(A, B):
    return A + B #just summing them up

A = np.array([0, 1, 2, 3, 4])
B = np.array([0, 1, 2, 3, 4])
C = add_with_numpy(A, B)
print(C)
print("Conclusion: When I used the mathematical function after importing NumPy, it sped up the process of calculating thanks to avoiding the loop and made the code simplier and shorter.")

[0 2 4 6 8]
Conclusion: When I used the mathematical function after importing NumPy, it sped up the process of calculating thanks to avoiding the loop and made the code simplier and shorter.


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [816]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [817]:
# Use this cell for your code
arr = np.arange(100)
arr_reshaped = arr.reshape(10, 10) # Reshaping it into a 10x10 array from create 1D array
print(arr_reshaped)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [818]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [819]:
# Use this cell for your code
row_pattern = np.array([0, 1] * 5)
arr = np.tile(row_pattern, (10, 1)).astype(float)
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


3. Create the following array (D):

In [820]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [821]:
# Use this cell for your code
D = 1 - np.eye(10)
print(D)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [822]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [823]:
# Use this cell for your code
E = 1 - np.flipud(np.eye(10))
print(E)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [824]:
# Use this cell for your code
DE = np.matmul(D, E)

# Determinants
det_DE = np.linalg.det(DE)
det_D_times_det_E = np.linalg.det(D) * np.linalg.det(E)

print("det(DE) =", det_DE)
print("det(D) * det(E) =", det_D_times_det_E)
print("if we round up the results to integer numbers, then they're both -81 and it suits the condition.")

det(DE) = -81.0000000000001
det(D) * det(E) = -81.0
if we round up the results to integer numbers, then they're both -81 and it suits the condition.


-- *Use this markdown cell for your written answer* --

If we round the results to integers, both are -81, which matches the expected result.
Out of given result, I can assume that the determinant of a product of two matrices is always equal to the product of their determinants. That's why it won't be a coincidence as it's based on the logic of linear algebra.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [825]:
# Use this cell for your code
from sklearn.datasets import fetch_california_housing
import pandas as pd

# Loading the dataset and saving it
data = fetch_california_housing(as_frame=True)
df = data.frame
df.to_csv('california_housing.csv', index=False)
print("Dataset saved as 'california_housing.csv'")
print(df.head()) #just want to see all columns and a few first rows

Dataset saved as 'california_housing.csv'
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422  


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [826]:
# Use this cell for your code
# Finding indices where AveBedrms > 2
indices = np.where(df['AveBedrms'] > 2)[0]  # [0] to get the array of indices
count = len(indices)
print("First few indices:", indices[:10])
print("Number of houses with average bedrooms > 2:", count)

First few indices: [ 710 1023 1024 1030 1102 1233 1234 1235 1236 1238]
Number of houses with average bedrooms > 2: 235


3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [827]:
# Use this cell for your code
mask = (df['HouseAge'] >= 1) & (df['HouseAge'] <= 3)
selected_rows = df[mask]
print("Number of houses with house age between 1 and 3:", selected_rows.shape[0])

Number of houses with house age between 1 and 3: 124


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [828]:
# Use this cell for your code
filtered = df[df['MedHouseVal'] > 0.25]
mean_population = filtered['Population'].mean()
print("Mean population for houses with median house value > 25000 USD:", mean_population)

Mean population for houses with median house value > 25000 USD: 1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [829]:
# Use this cell for your code
import gzip
import json

with gzip.open("Automotive_5.json.gz", 'rt', encoding='utf-8') as f:
    reviews = [json.loads(line) for line in f]

print(f"Total reviews loaded: {len(reviews)}")
print("First review:", reviews[0]['reviewText'])

Total reviews loaded: 1711519
First review: After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  Then the charge / sync cable goes through the hole and you can charge from the side.  When used in landscape position this stand does make more sense so I'm upgrading this review from 2 stars to 4 stars (which I rarely do, but in this case user error) with a star off for lack of documentation.  Manufacturer has said he will include directions and I would also encourage him to update the photos on Amazon with more examples of how this can be used.  The wood quality is indeed good and it's a sturdy little stand.  I'm trying to think of when I'd actually use this stand... perhaps for Facetime chats.  I also think it would be useful for someone in an open office environment if they want to keep their phone on th

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [830]:
# Use this cell for your code
review_texts = [r["reviewText"].lower() for r in reviews if "reviewText" in r]
print("First review (downcased):")
print(review_texts[0])

First review (downcased):
after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see a

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [831]:
# Use this cell for your code
import string

# Loading the stopwords
with open("stopwords-en.txt", "r") as f:
    stopwords = set(f.read().splitlines())

# Functions to clean a review
def clean_review(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    words = [word for word in text.split() if word not in stopwords]
    return " ".join(words)

# Applying cleaning to all reviews
cleaned_reviews = [clean_review(r["reviewText"]) for r in reviews if "reviewText" in r]

print("First cleaned review:")
print(cleaned_reviews[0])

First cleaned review:
wrote review manufacturer contacted explained use instead current picture amazon phone placed vertically actually use stand phone placed horizontally charge sync cable goes hole charge used landscape position stand does make sense im upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer said include directions encourage update photos amazon examples used wood quality good sturdy little stand im trying think id actually use stand facetime chats think useful open office environment want phone desk alerts notifications easily hope updated review helps original review throwing stand garbage crafted nice wood functional near tell does come instructions product description confusing english poorly translated chinese iphone sits stand just fine stand way plug plug stand blocks turn iphone plug just looks strange im sure hole stand supposed included plastic feet instructions affixed stand began wobble figure work thing post review fa

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [834]:
# Use this cell for your code
import nltk
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

# Functions to clean + stem a review
def clean_and_stem(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    words = [w for w in text.split() if w not in stopwords]
    # Applying stemming
    stemmed = [stemmer.stem(w) for w in words]
    return " ".join(stemmed)

# Applying to all reviews
stemmed_reviews = [clean_and_stem(r["reviewText"]) for r in reviews if "reviewText" in r]

print("First review after stemming:")
print(stemmed_reviews[0])

First review after stemming:
wrote review manufactur contact explain use instead current pictur amazon phone place vertic actual use stand phone place horizont charg sync cabl goe hole charg use landscap posit stand doe make sens im upgrad review 2 star 4 star rare case user error star lack document manufactur said includ direct encourag updat photo amazon exampl use wood qualiti good sturdi littl stand im tri think id actual use stand facetim chat think use open offic environ want phone desk alert notif easili hope updat review help origin review throw stand garbag craft nice wood function near tell doe come instruct product descript confus english poorli translat chines iphon sit stand just fine stand way plug plug stand block turn iphon plug just look strang im sure hole stand suppos includ plastic feet instruct affix stand began wobbl figur work thing post review far im concern box experi terribl sorri recommend sampl provid exchang honest review


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [835]:
# Use this cell for your code
# Combining data into a list of tuples (rating, text)
processed_data = [
    (r["overall"], clean_and_stem(r["reviewText"]))
    for r in reviews if "reviewText" in r and "overall" in r
]

# Separating into positive (4–5) and negative (1–2)
positive_reviews = [text for rating, text in processed_data if rating in [4, 5]]
negative_reviews = [text for rating, text in processed_data if rating in [1, 2]]

# Saving to files
with open("pos.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(positive_reviews))

with open("neg.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(negative_reviews))

print(f"Saved {len(positive_reviews)} positive reviews to pos.txt")
print(f"Saved {len(negative_reviews)} negative reviews to neg.txt")

Saved 1475766 positive reviews to pos.txt
Saved 132261 negative reviews to neg.txt


## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

In [856]:
import sqlite3
import pandas as pd

db_path = r"C:\Users\Omistaja\Downloads\northwind2000-simplified.sqlite"
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Listing tables to confirm the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in the database:", tables)

Tables in the database: [('Categories',), ('sqlite_sequence',), ('Customers',), ('Employees',), ('OrderDetails',), ('Orders',), ('Products',), ('Shippers',), ('Suppliers',)]


In [857]:
query = """
SELECT FirstName, LastName, HireDate
FROM Employees
WHERE HireDate > '1994-01-01';
"""
df = pd.read_sql_query(query, conn)
print(df)

  FirstName   LastName    HireDate
0    Robert       King  1994-01-02
1     Laura   Callahan  1994-03-05
2      Anne  Dodsworth  1994-11-15


In [858]:
query = """
SELECT CustomerID, COUNT(*) as NumOrders
FROM Orders
GROUP BY CustomerID;
"""
df = pd.read_sql_query(query, conn)
print(df)

   CustomerID  NumOrders
0       ALFKI          6
1       ANATR          4
2       ANTON          7
3       AROUT         13
4       BERGS         18
..        ...        ...
84      WARTH         15
85      WELLI          9
86      WHITC         14
87      WILMK          7
88      WOLZA          7

[89 rows x 2 columns]


In [859]:
query = """
SELECT DISTINCT c.ContactName
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
WHERE p.ProductName = 'Chai';
"""
df = pd.read_sql_query(query, conn)
print(df)

                ContactName
0               Horst Kloss
1              Paula Wilson
2               Fran Wilson
3               Rita Müller
4       Guillermo Fernández
5                 Yang Wang
6            Lúcia Carvalho
7            Annette Roulet
8          Isabel de Castro
9            Renate Messner
10         Pirkko Koskitalo
11     Miguel Angel Paolino
12           Jean Fresnière
13           Janine Labrune
14  Zbyszek Piestrzeniewicz
15       Frédérique Citeaux
16         Patricia McKenna
17       Christina Berglund
18           Jose Pavarotti
19         Felipe Izquierdo
20           Simon Crowther
21         Carlos Hernández
22               Hari Kumar
23            Paula Parente
24        José Pedro Freyre
25        Elizabeth Lincoln
26                 Liu Wong
27          Matti Karttunen
28            Howard Snyder
29         Pascale Cartrain
30                Ann Devon


In [860]:
query = """
SELECT *
FROM Orders
WHERE ShippedDate IS NULL;
"""
df = pd.read_sql_query(query, conn)
print(df)

    OrderID CustomerID  EmployeeID                OrderDate  \
0     11008      ERNSH           7  1998-04-08 00:00:00.000   
1     11019      RANCH           6  1998-04-13 00:00:00.000   
2     11039      LINOD           1  1998-04-21 00:00:00.000   
3     11040      GREAL           4  1998-04-22 00:00:00.000   
4     11045      BOTTM           6  1998-04-23 00:00:00.000   
5     11051      LAMAI           7  1998-04-27 00:00:00.000   
6     11054      CACTU           8  1998-04-28 00:00:00.000   
7     11058      BLAUS           9  1998-04-29 00:00:00.000   
8     11059      RICAR           2  1998-04-29 00:00:00.000   
9     11061      GREAL           4  1998-04-30 00:00:00.000   
10    11062      REGGC           4  1998-04-30 00:00:00.000   
11    11065      LILAS           8  1998-05-01 00:00:00.000   
12    11068      QUEEN           8  1998-05-04 00:00:00.000   
13    11070      LEHMS           2  1998-05-05 00:00:00.000   
14    11071      LILAS           1  1998-05-05 00:00:00

In [861]:
query = """
SELECT CustomerID, COUNT(*) as NumOrders
FROM Orders
GROUP BY CustomerID
ORDER BY NumOrders DESC
LIMIT 1;
"""
df = pd.read_sql_query(query, conn)
print(df)

  CustomerID  NumOrders
0      SAVEA         31


**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**